kubernetesClusterDomain: cluster.local
operator:
  serviceAccount:
    annotations: {}
virtOperator:
  nodeSelector:
    kubernetes.io/os: linux
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  replicas: 2
  virtOperator:
    args:
    - --port
    - "8443"
    - -v
    - "2"
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault
    env:
      kubevirtVersion: v1.3.1
      virtOperatorImage: quay.io/kubevirt/virt-operator:v1.3.1
    image:
      repository: quay.io/kubevirt/virt-operator
      tag: v1.3.1
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 10m
        memory: 450Mi
