apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubevirt-chart.fullname" . }}-operator
  labels:
    kubevirt.io: ""
  {{- include "kubevirt-chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.operator.serviceAccount.annotations | nindent 4 }}